apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ashu-app-deploy
  name: ashu-app-deploy
spec:
  replicas: 1 # number of pods 
  selector:
    matchLabels:
      app: ashu-app-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ashu-app-deploy
    spec:
      containers:
      - image: asia-docker.pkg.dev/vodafone-devsecops/vodafone-webapp-images/ashuwebapp:v1
        name: nginx
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        resources: {}
status: {}