options: 
  logging: CLOUD_LOGGING_ONLY
steps:
  # STEP 1 
  # using code build internal command to build image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'ashuwebapp:v1', '.']
  # Step 2 
  # do SAST in build container image with trivy
  - name: 'aquasec/trivy:latest'
    args: ['image' ,'--severity' ,'HIGH,CRITICAL' ,'--format', 'json',  '--output' , '/tmp/ashu_imagescan.json','--exit-code','1' ,'ashuwebapp:v1'] 
    
  # STEP 3 creating containers 
  # creating container 
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', '-idt', '--name', 'ashuc11',
     '-p' ,'1234:80', '--rm' ,'ashuwebapp:v1'
    ]